#!/usr/bin/env bash
set -euo pipefail

command -v python3 >/dev/null || { echo "python3 required" >&2; exit 1; }

colors_css=~/.config/waybar/colors.css
obsidian_json=~/.config/obsidian/obsidian.json

# Parse base16 colors from waybar colors.css
declare -A c
while IFS= read -r line; do
    if [[ "$line" =~ @define-color\ (base[0-9A-Fa-f]+)\ (#[0-9a-fA-F]+)\; ]]; then
        c[${BASH_REMATCH[1]}]="${BASH_REMATCH[2]}"
    fi
done < "$colors_css"

# Same mapping for both dark and light — tinty switches the scheme itself
vars="
    --background-primary: ${c[base00]};
    --background-primary-alt: ${c[base01]};
    --background-secondary: ${c[base00]};
    --background-secondary-alt: ${c[base01]};
    --background-modifier-border: ${c[base02]};
    --background-modifier-form-field: ${c[base01]};
    --background-modifier-form-field-highlighted: ${c[base02]};
    --background-modifier-success: ${c[base0B]};
    --background-modifier-error: ${c[base08]};
    --text-accent: ${c[base0D]};
    --text-accent-hover: ${c[base0E]};
    --text-normal: ${c[base05]};
    --text-muted: ${c[base04]};
    --text-faint: ${c[base03]};
    --text-error: ${c[base08]};
    --text-highlight-bg: color-mix(in srgb, ${c[base0A]} 30%, transparent);
    --text-selection: ${c[base02]};
    --text-on-accent: ${c[base00]};
    --interactive-normal: ${c[base01]};
    --interactive-hover: ${c[base02]};
    --interactive-accent: ${c[base0D]};
    --interactive-accent-hover: ${c[base0E]};
    --interactive-success: ${c[base0B]};
    --scrollbar-active-thumb-bg: ${c[base03]};
    --scrollbar-bg: ${c[base00]};
    --scrollbar-thumb-bg: ${c[base02]};
"

theme_css="/* Base16 theme - generated by tinty hook */

.theme-dark {${vars}}

.theme-light {${vars}}

body {
    --font-monospace: 'MesloLGS Nerd Font', monospace;
}

.suggestion-item.is-selected {
    background-color: var(--background-primary-alt);
}
"

# Apply to all vaults
python3 -c "
import json, pathlib
with open('$obsidian_json') as f:
    vaults = json.load(f).get('vaults', {})
for v in vaults.values():
    p = pathlib.Path(v['path']) / '.obsidian' / 'themes'
    if p.parent.exists():
        p.mkdir(exist_ok=True)
        print(p / 'base16.css')
" | while IFS= read -r dest; do
    echo "$theme_css" > "$dest"
done
