[".config/mutt/base16-mutt"]
type = "git-repo"
url = "https://github.com/josephholsten/base16-mutt.git"
refreshPeriod = "168h"

[".local/share/antidote-src"]
type = "git-repo"
url = "https://github.com/mattmc3/antidote.git"
refreshPeriod = "168h"
