.DEFAULT_GOAL := help

.PHONY: build

build: ## build this project
    echo build

help: ## show this help for targets
	@grep -E --no-filename '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
