# Global settings
shell = "zsh -c '{}'"
default-scheme = "base16-darktooth"

[[items]]
name = "base16-shell"
path = "https://github.com/tinted-theming/base16-shell"
themes-dir = "scripts"
hook = "source %f"

[[items]]
name = "base16-sway"
path = "https://github.com/rkubosz/base16-sway"
themes-dir = "themes"
hook = "cp -f %f ~/.config/sway/base16.config && /usr/bin/swaymsg reload"

[[items]]
path = "https://github.com/tinted-theming/base16-alacritty"
name = "base16-alacritty"
themes-dir = "colors-256"
hook = "cp -f %f ~/.config/alacritty/colors.toml"

[[items]]
path = "https://github.com/tinted-theming/base16-waybar"
name = "base16-waybar"
themes-dir = "colors"
hook = "cp -f %f ~/.config/waybar/colors.css"

[[items]]
path = "https://github.com/tinted-theming/tinted-fzf"
name = "tinted-fzf"
themes-dir = "sh"
hook = "source %f"

[[items]]
path = "https://git.sr.ht/~knezi/base16-wofi"
name = "base16-wofi"
themes-dir = "themes"
hook = "cp -f %f ~/.config/wofi/style.css"

