#!/bin/bash

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"
BRANCH_NAME=$(echo ${BRANCH_NAME} | grep -o -i -E "[A-Z]+-[0-9]+" | tr '[a-z]' '[A-Z]')
BRANCH_NAME=$(echo ${BRANCH_NAME} | sed -e 's/[[:space:]]*$//')
BRANCH_NAME=$(echo ${BRANCH_NAME} | tr '[:blank:]' ',')
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)

if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  sed -i.bak -e "1s/^/[$BRANCH_NAME] /" $1
fi
