[Service]

# Load encrypted credentials into a protected memory area
LoadCredentialEncrypted=restic-pass:/etc/restic/repo-password.cred
LoadCredentialEncrypted=nas-repo:/etc/restic/nas-repo.cred

# Capabilities configuration
AmbientCapabilities=CAP_DAC_READ_SEARCH
CapabilityBoundingSet=CAP_DAC_READ_SEARCH
