[general]
import = ["~/.config/alacritty/colors.toml"]

[font]
size = 10.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[cursor]
style = "Beam"

[window]
opacity = 0.90
