import = [
"~/.config/alacritty/colors.toml",
]

[font]
size = 12.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[cursor]
style = "Beam"

[window]
opacity = 0.90


