#!/usr/bin/env bash
set -euo pipefail

src="${1:-$HOME/.config/waybar/colors.css}"
profiles_dir="$HOME/.mozilla/firefox"

[[ -f "$src" ]] || exit 0
[[ -d "$profiles_dir" ]] || exit 0

get() { sed -n "s/@define-color $1 \(#[0-9a-fA-F]*\);/\1/p" "$src"; }

css="/* Base16 theme - generated by tinty hook */
:root {
    --base00: $(get base00);
    --base01: $(get base01);
    --base02: $(get base02);
    --base03: $(get base03);
    --base04: $(get base04);
    --base05: $(get base05);
    --base06: $(get base06);
    --base07: $(get base07);
    --base08: $(get base08);
    --base09: $(get base09);
    --base0A: $(get base0A);
    --base0B: $(get base0B);
    --base0C: $(get base0C);
    --base0D: $(get base0D);
    --base0E: $(get base0E);
    --base0F: $(get base0F);
}

/* Toolbar and tab bar */
#navigator-toolbox {
    background-color: var(--base01) !important;
}

/* Tab bar background */
#titlebar {
    background-color: var(--base00) !important;
}

/* Active tab */
.tabbrowser-tab[selected] .tab-background {
    background-color: var(--base01) !important;
}

/* Inactive tabs */
.tabbrowser-tab:not([selected]) .tab-background {
    background-color: var(--base00) !important;
}

/* Tab text */
.tabbrowser-tab {
    color: var(--base05) !important;
}

/* URL bar */
#urlbar-background {
    background-color: var(--base00) !important;
    border-color: var(--base02) !important;
}

#urlbar-input {
    color: var(--base05) !important;
}

/* Sidebar */
#sidebar-header, #sidebar-box {
    background-color: var(--base00) !important;
    color: var(--base05) !important;
}

/* Findbar */
findbar {
    background-color: var(--base01) !important;
    color: var(--base05) !important;
}
"

# Deploy to all profiles with chrome dir
for profile in "$profiles_dir"/*.default-release "$profiles_dir"/*.default; do
    [[ -d "$profile" ]] || continue
    mkdir -p "$profile/chrome"
    echo "$css" > "$profile/chrome/userChrome.css"
done
