#!/usr/bin/env bash
set -euo pipefail

src="${1:-$HOME/.config/waybar/colors.css}"
profiles_dir="${HOME}/.mozilla/firefox"
[[ -d "$profiles_dir" ]] || profiles_dir="${HOME}/.config/mozilla/firefox"

[[ -f "$src" ]] || exit 0
[[ -d "$profiles_dir" ]] || exit 0

get() { sed -n "s/@define-color $1 \(#[0-9a-fA-F]*\);/\1/p" "$src"; }

css="/* Base16 theme - generated by tinty hook */
@namespace url(\"http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul\");

:root {
    --toolbar-bgcolor: $(get base01) !important;
    --toolbar-color: $(get base05) !important;
    --toolbar-field-background-color: $(get base00) !important;
    --toolbar-field-color: $(get base05) !important;
    --toolbar-field-border-color: $(get base02) !important;
    --toolbar-field-focus-background-color: $(get base00) !important;
    --toolbar-field-focus-color: $(get base05) !important;
    --lwt-toolbar-field-highlight: $(get base02) !important;
    --lwt-accent-color: $(get base00) !important;
    --lwt-text-color: $(get base05) !important;
    --tab-selected-bgcolor: $(get base01) !important;
    --tab-selected-textcolor: $(get base05) !important;
    --lwt-tab-text: $(get base04) !important;
    --arrowpanel-background: $(get base00) !important;
    --arrowpanel-color: $(get base05) !important;
    --arrowpanel-border-color: $(get base02) !important;
    --sidebar-background-color: $(get base00) !important;
    --sidebar-text-color: $(get base05) !important;
    --urlbar-box-bgcolor: $(get base00) !important;
}

/* Navigator toolbox */
#navigator-toolbox {
    background: $(get base00) !important;
}

/* Tabs toolbar */
#TabsToolbar {
    background: $(get base00) !important;
}

/* Selected tab */
.tab-background[selected] {
    background: $(get base01) !important;
}

/* URL bar */
#urlbar-background {
    background: $(get base00) !important;
}

/* Findbar */
findbar {
    background: $(get base01) !important;
    color: $(get base05) !important;
}
"

# Deploy to all profiles with chrome dir
for profile in "$profiles_dir"/*.default-release "$profiles_dir"/*.default; do
    [[ -d "$profile" ]] || continue
    mkdir -p "$profile/chrome"
    echo "$css" > "$profile/chrome/userChrome.css"
done
