#!/usr/bin/env bash
set -euo pipefail

src="${1:-$HOME/.config/waybar/colors.css}"
profiles_dir="${HOME}/.mozilla/firefox"
[[ -d "$profiles_dir" ]] || profiles_dir="${HOME}/.config/mozilla/firefox"

[[ -f "$src" ]] || exit 0
[[ -d "$profiles_dir" ]] || exit 0

get() { sed -n "s/@define-color $1 \(#[0-9a-fA-F]*\);/\1/p" "$src"; }

css="/* Base16 theme - generated by tinty hook */

:root {
    --toolbar-bgcolor: $(get base01) !important;
    --toolbar-color: $(get base05) !important;
    --toolbar-field-background-color: $(get base00) !important;
    --toolbar-field-color: $(get base05) !important;
    --toolbar-field-border-color: $(get base02) !important;
    --toolbar-field-focus-background-color: $(get base00) !important;
    --toolbar-field-focus-color: $(get base05) !important;
    --lwt-toolbar-field-highlight: $(get base02) !important;
    --lwt-accent-color: $(get base00) !important;
    --lwt-text-color: $(get base05) !important;
    --tab-selected-bgcolor: $(get base01) !important;
    --tab-selected-textcolor: $(get base05) !important;
    --lwt-tab-text: $(get base04) !important;
    --arrowpanel-background: $(get base00) !important;
    --arrowpanel-color: $(get base05) !important;
    --arrowpanel-border-color: $(get base02) !important;
    --sidebar-background-color: $(get base00) !important;
    --sidebar-text-color: $(get base05) !important;
    --urlbar-box-bgcolor: $(get base00) !important;
}

/* Navigator toolbox */
#navigator-toolbox {
    background: $(get base00) !important;
}

/* Navigation bar (around address bar) */
#nav-bar {
    background: $(get base01) !important;
}

/* Tabs toolbar */
#TabsToolbar {
    background: $(get base00) !important;
}

/* Selected tab */
.tab-background[selected] {
    background: $(get base01) !important;
}

/* URL bar */
#urlbar-background {
    background: $(get base00) !important;
}

/* Findbar */
findbar {
    background: $(get base01) !important;
    color: $(get base05) !important;
}

/* Sidebar */
#sidebar-box,
#sidebar-header {
    background: $(get base00) !important;
    color: $(get base05) !important;
}

#sidebar {
    background: $(get base00) !important;
    color: $(get base05) !important;
}

/* Bookmarks toolbar */
#PersonalToolbar {
    background: $(get base00) !important;
    color: $(get base05) !important;
}

#PlacesToolbarItems toolbarbutton {
    color: $(get base05) !important;
}

/* Sidebar panel content */
#sidebar-box *|*:root {
    --lwt-sidebar-background-color: $(get base00) !important;
    --lwt-sidebar-text-color: $(get base05) !important;
}

#sidebar-main,
#sidebar-main .sidebar-panel {
    background: $(get base00) !important;
    color: $(get base05) !important;
}

/* Menus and popups */
menupopup,
panel,
.panel-arrowcontent,
panelview,
#appMenu-popup,
#customizationui-widget-panel,
#widget-overflow {
    background: $(get base00) !important;
    color: $(get base05) !important;
}

menuitem,
menu {
    color: $(get base05) !important;
}

menuitem:hover,
menu[_moz-menuactive] {
    background: $(get base02) !important;
}

/* Autocomplete popup (URL suggestions) */
#PopupAutoComplete,
.autocomplete-richlistbox,
#urlbar .urlbarView {
    background: $(get base00) !important;
    color: $(get base05) !important;
}

.urlbarView-row:hover,
.urlbarView-row[selected] {
    background: $(get base02) !important;
}

/* Compact tabs */
#tabbrowser-tabs {
    --tab-min-height: 28px !important;
}
#TabsToolbar {
    height: 28px !important;
}
"

# Deploy to all profiles with chrome dir
for profile in "$profiles_dir"/*.default-release "$profiles_dir"/*.default; do
    [[ -d "$profile" ]] || continue
    mkdir -p "$profile/chrome"
    echo "$css" > "$profile/chrome/userChrome.css"

    # userContent.css for sidebar and internal pages
    cat > "$profile/chrome/userContent.css" << CONTENT
/* Base16 theme for Firefox content areas */
@-moz-document url-prefix("chrome://browser/content/places/") {
    body, #places {
        background-color: $(get base00) !important;
        color: $(get base05) !important;
    }
    treechildren {
        background-color: $(get base00) !important;
        color: $(get base05) !important;
    }
}

@-moz-document url("about:blank"), url("about:newtab"), url("about:home") {
    body {
        background-color: $(get base00) !important;
    }
}
CONTENT
done
