"$schema" = 'https://starship.rs/config-schema.json'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
symbol = "☸ "
detect_env_vars = ['KUBECONFIG', 'KUBERNETES_SHOW']
contexts = [
  { context_pattern = ".*dev.*", style = "bold green" },
  { context_pattern = ".*test.*", style = "bold yellow" },
  { context_pattern = ".*(prod|production).*", style = "bold red" },
]

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[profiles]
transient = """$character"""

[git_branch]
style = "purple"
symbol = " "

[git_commit]
tag_symbol = '  '

[cmd_duration]
style = "yellow"

[directory]
style = "cyan"
read_only = " 󰌾"

[docker_context]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[terraform]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[dart]
symbol = " "

[kotlin]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[php]
symbol = " "

[package]
symbol = "󰏗 "

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "
